### ISSUE TITLE
make diff call insensitive against line-ending changes

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/quickcheck#1]
As discussed before in the statcheck context, we should probably make diff insensitive against different line-endings, or else quickcheck's results depend on them being generated on a *NIX system or e.g. a MSYS2 shell. Relevant options include `--strip-trailing-cr` and `--ignore-all-space`, though I am not sure which of these are GNU-isms and which are required by POSIX.

**Comment by fragglet** [comment]
Now fixed I believe.
